image: $CI_ARTIFACTORY_URL_CLOUD_BASE/docker:18.09
services:
  - $CI_ARTIFACTORY_URL_CLOUD_BASE/docker:18.09-dind
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  except:
    - merge_requests
    - pushes
    - tags
    - triggers
    - schedules
  only:
    variables:
      - $RUN_TYPE == "build_image"
  script:
    - docker login $CI_ARTIFACTORY_URL_CLOUD -u $CI_ARTIFACTORY_USER -p $CI_ARTIFACTORY_PASSWORD
    - |
      docker build \
      --build-arg CI_ARTIFACTORY_USER="$CI_ARTIFACTORY_USER" \
      --build-arg CI_ARTIFACTORY_PASSWORD="$CI_ARTIFACTORY_PASSWORD" \
      --build-arg CI_BUILD_TAG="$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID" \
      --build-arg CI_ARTIFACTORY_URL="$CI_ARTIFACTORY_URL" \
      --build-arg CI_ARTIFACTORY_URL_CLOUD_BASE="$CI_ARTIFACTORY_URL_CLOUD_BASE" \
      -t $CI_ARTIFACTORY_URL_CLOUD/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID .
    - docker push $CI_ARTIFACTORY_URL_CLOUD/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    - echo DOCKER_IMAGE=$CI_ARTIFACTORY_URL_CLOUD/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID >> build.env
  artifacts:
    reports:
      dotenv: build.env

# Запускаем тесты
run_regression_tests_job: #Test_&_send:
  stage: test
  image:
    name: artifactory.exportcenter.ru/docker/sub-service/autotests/rec_autotests:master-178474
    entrypoint: [""]  # Переопределение "точки входа" в контейнер который запускается ранером при сборке
  except:
    - merge_requests
    - pushes
    - tags
    - triggers
    - schedules
  only:
    variables:
      - $RUN_TYPE == "testng"
  artifacts:          # Имеет смысл в случае ошибки при выполнении теста результат пихать в артефакты гитлаба для анализа
    expire_in: 1 days
    when: on_failure
    paths:
      - mvn/**/*
      - result.json
  before_script:
    - mkdir -p /share && mount.cifs //10.5.1.87/share /share -o username=share,password=aij7zieYAeng2gee,file_mode=0766,dir_mode=0766
    - export TZ=Europe/Moscow
  script:
    - echo $RUN_TYPE
    - whoami
    - chmod +x ./send_results.sh
    - mvn test -Dsurefire.suiteXmlFiles=testng.xml || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
    - ./send_results.sh || echo "[ERROR] Отправка результатов в Allure завершилась с ошибкой"
