---
image:
  name: maven:3.8-openjdk-8
  entrypoint: [""]  # Переопределение "точки входа" в контейнер который запускается ранером при сборке

variables:
  #GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  #GRADLE_USER_HOME: /build/.gradle

stages:
  - test

# Запускаем тесты
run_regression_tests_job: #Test_&_send:
  except:
    - merge_requests
    - pushes
#    - tags
#    - triggers
#    - schedules
  only:
    variables:
      - $RUN_TYPE == "regression_tests"
  artifacts:          # Имеет смысл в случае ошибки при выполнении теста результат пихать в артефакты гитлаба для анализа
    expire_in: 1 days
    when: on_failure
    paths:
      - mvn/**/*
      - result.json
#  before_script:
#    - mkdir -p /share && mount.cifs //172.31.197.220/atst /share -o username=User,password=Start123,file_mode=0766,dir_mode=0766
#    - export TZ=Europe/Moscow
  script:
    - echo $RUN_TYPE
#    - mvn test -DsuiteXmlFile=testng.xml || echo "[ERROR]  Выполнение тестов завершилось с ошибкой"
    - mvn test -Dsurefire.suiteXmlFiles=testng.xml || echo "[ERROR]  Выполнение тестов завершилось с ошибкой"
#    - javac src/test/java/framework/SuiteBuilderAndRunner.java
#    - mvn test -Dsurefire.suiteXmlFiles=smoke_tests_2.xml || echo "[ERROR]  Выполнение тестов завершилось с ошибкой"
#    - mvn test -Dsurefire.suiteXmlFiles=smoke_tests.xml,smoke_tests2.xml || echo "[ERROR]  Выполнение тестов завершилось с ошибкой"
    #- ./Send_results_to_jira.sh || echo "[ERROR]   Отправка результатов в Jira завершилась с ошибкой"
    - ./send_results.sh || echo "[ERROR]   Отправка результатов в Allure завершилась с ошибкой"
  stage: test
#  tags: [gitlabw-inf-07]
